/*
 * Copyright sablintolya@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.ma1uta.matrix.identity.api;

import io.github.ma1uta.matrix.ErrorResponse;
import io.github.ma1uta.matrix.identity.model.associations.ValidationResponse;
import io.github.ma1uta.matrix.identity.model.session.EmailRequestToken;
import io.github.ma1uta.matrix.identity.model.session.SubmitToken;
import io.github.ma1uta.matrix.identity.model.validation.PublishRequest;
import io.github.ma1uta.matrix.identity.model.validation.PublishResponse;
import io.github.ma1uta.matrix.thirdpid.SessionResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import javax.ws.rs.Consumes;
import javax.ws.rs.FormParam;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.container.AsyncResponse;
import javax.ws.rs.container.Suspended;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.UriInfo;

/**
 * Deprecated API.
 */
@Deprecated
@Path("/_matrix/identity/api/v1")
@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
@Produces(MediaType.APPLICATION_JSON)
public interface DeprecatedApi {

    /**
     * Create a session for validating an email address.
     * <br>
     * The identity server will send an email containing a token. If that token is presented to the identity server in the future,
     * it indicates that that user was able to read the email for that email address, and so we validate ownership of the email address.
     * <br>
     * Note that homeservers offer APIs that proxy this API, adding additional behaviour on top, for example,
     * /register/email/requestToken is designed specifically for use when registering an account and therefore will inform the user
     * if the email address given is already registered on the server.
     * <br>
     * Return: {@link SessionResponse}.
     * <p> Status code 200: Session created.</p>
     * <p>Status code 400: An error ocurred. Some possible errors are:</p>
     * <ul>
     * <li>M_INVALID_EMAIL: The email address provided was invalid.</li>
     * <li>M_EMAIL_SEND_ERROR: The validation email could not be sent.</li>
     * </ul>
     *
     * @param clientSecret  Required. A unique string generated by the client, and used to identify the validation attempt.
     *                      It must be a string consisting of the characters [0-9a-zA-Z.=_-]. Its length must not exceed 255
     *                      characters and it must not be empty.
     * @param email         Required. The email address to validate.
     * @param sendAttempt   Required. The server will only send an email if the send_attempt is a number greater than the most recent
     *                      one which it has seen, scoped to that email + client_secret pair. This is to avoid repeatedly sending the
     *                      same email in the case of request retries between the POSTing user and the identity server. The client
     *                      should increment this value if they desire a new email (e.g. a reminder) to be sent.
     * @param nextLink      Optional. When the validation is completed, the identity server will redirect the user to this URL.
     * @param uriInfo       Request Information.
     * @param httpHeaders   Http headers.
     * @param asyncResponse Asynchronous response.
     * @deprecated in favor of {@link SessionApi#createEmailSession(EmailRequestToken, UriInfo, HttpHeaders, AsyncResponse)}.
     */
    @Deprecated
    @Operation(
        summary = "Create a session for validating an email address.",
        description = "The identity server will send an email containing a token. If that token is presented to the identity server in"
            + " the future, it indicates that that user was able to read the email for that email address, and so we validate ownership"
            + " of the email address.\nNote that homeservers offer APIs that proxy this API, adding additional behaviour on top,"
            + " for example,/register/email/requestToken is designed specifically for use when registering an account and therefore will"
            + " inform the user if the email address given is already registered on the server.",
        responses = {
            @ApiResponse(
                responseCode = "200",
                description = "Session created.",
                content = @Content(
                    schema = @Schema(
                        implementation = SessionResponse.class
                    )
                )
            ),
            @ApiResponse(
                responseCode = "400",
                description = "An error ocurred.",
                content = @Content(
                    schema = @Schema(
                        implementation = ErrorResponse.class
                    )
                )
            )

        }
    )
    @POST
    @Path("/validate/email/requestToken")
    void createEmailSessionDeprecated(
        @Parameter(
            description = "A unique string generated by the client, and used to identify the validation attempt. It must be a string"
                + " consisting of the characters [0-9a-zA-Z.=_-]. Its length must not exceed 255 characters and it must not be empty.",
            required = true
        ) @FormParam("client_secret") String clientSecret,
        @Parameter(
            description = "The email address to validate.",
            required = true
        ) @FormParam("email") String email,
        @Parameter(
            name = "send_attempt",
            description = "The server will only send an email if the send_attempt is a number greater than the most recent"
                + " one which it has seen, scoped to that email + client_secret pair. This is to avoid repeatedly sending the"
                + " same email in the case of request retries between the POSTing user and the identity server. The client"
                + " should increment this value if they desire a new email (e.g. a reminder) to be sent.",
            required = true
        ) @FormParam("send_attempt") Long sendAttempt,
        @Parameter(
            name = "next_link",
            description = "When the validation is completed, the identity server will redirect the user to this URL."
        ) @FormParam("next_link") String nextLink,

        @Context UriInfo uriInfo,
        @Context HttpHeaders httpHeaders,
        @Suspended AsyncResponse asyncResponse
    );

    /**
     * Validate ownership of an email address.
     * <br>
     * If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address is
     * considered to have been validated. This does not publish any information publicly, or associate the email address with any
     * Matrix user ID. Specifically, calls to /lookup will not show a binding.
     * <br>
     * The identity server is free to match the token case-insensitively, or carry out other mapping operations such as unicode
     * normalisation. Whether to do so is an implementation detail for the identity server. Clients must always pass on the token
     * without modification.
     * <br>
     * Return: {@link ValidationResponse}.
     * <p>Status code 200: The success of the validation.</p>
     *
     * @param sid           Required. The session ID, generated by the requestToken call.
     * @param clientSecret  Required. The client secret that was supplied to the requestToken call.
     * @param token         Required. The token generated by the requestToken call and emailed to the user.
     * @param uriInfo       Request Information.
     * @param httpHeaders   Http headers.
     * @param asyncResponse Asynchronous response.
     * @deprecated in favor of {@link SessionApi#postValidateEmail(SubmitToken, UriInfo, HttpHeaders, AsyncResponse)}.
     */
    @Deprecated
    @Operation(
        summary = "Validate ownership of an email address.",
        description = "If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address"
            + " is considered to have been validated. This does not publish any information publicly, or associate the email address with"
            + " any Matrix user ID. Specifically, calls to /lookup will not show a binding.\nThe identity server is free to match the token"
            + " case-insensitively, or carry out other mapping operations such as unicode normalisation. Whether to do so is"
            + " an implementation detail for the identity server. Clients must always pass on the token without modification.",
        responses = {
            @ApiResponse(
                responseCode = "200",
                description = "The success of the validation.",
                content = @Content(
                    schema = @Schema(
                        implementation = ValidationResponse.class
                    )
                )
            )
        }
    )
    @POST
    @Path("/validate/email/submitToken")
    void postValidateEmailDeprecated(
        @Parameter(
            description = "The session ID, generated by the requestToken call.",
            required = true
        ) @FormParam("sid") String sid,
        @Parameter(
            name = "client_secret",
            description = "The client secret that was supplied to the requestToken call.",
            required = true
        ) @FormParam("client_secret") String clientSecret,
        @Parameter(
            description = "The token generated by the requestToken call and emailed to the user.",
            required = true
        ) @FormParam("token") String token,

        @Context UriInfo uriInfo,
        @Context HttpHeaders httpHeaders,
        @Suspended AsyncResponse asyncResponse
    );

    /**
     * Create a session for validating a phone number.
     * <br>
     * The identity server will send an SMS message containing a token. If that token is presented to the identity server in the future,
     * it indicates that that user was able to read the SMS for that phone number, and so we validate ownership of the phone number.
     * <br>
     * Note that homeservers offer APIs that proxy this API, adding additional behaviour on top, for example, /register/msisdn/requestToken
     * is designed specifically for use when registering an account and therefore will inform the user if the phone number given is already
     * registered on the server.
     * <br>
     * Return: {@link SessionResponse}.
     * <p>Status code 200: Session created.</p>
     * <p>Status code 400: An error ocurred. Some possible errors are:</p>
     * <ul>
     * <li>M_INVALID_ADDRESS: The phone number provided was invalid.</li>
     * <li>M_SEND_ERROR: The validation SMS could not be sent.</li>
     * <li>M_DESTINATION_REJECTED: The identity server cannot deliver an SMS to the provided country or region.</li>
     * </ul>
     *
     * @param clientSecret  Required. A unique string generated by the client, and used to identify the validation attempt.
     *                      It must be a string consisting of the characters [0-9a-zA-Z.=_-]. Its length must not exceed 255
     *                      characters and it must not be empty.
     * @param country       Required. The two-letter uppercase ISO country code that the number in phone_number should be parsed as
     *                      if it were dialled from.
     * @param phoneNumber   Required. The phone number to validate.
     * @param sendAttempt   Required. The server will only send an SMS if the send_attempt is a number greater than the most recent
     *                      one which it has seen, scoped to that country + phone_number + client_secret triple. This is to avoid
     *                      repeatedly sending the same SMS in the case of request retries between the POSTing user and the identity
     *                      server. The client should increment this value if they desire a new SMS (e.g. a reminder) to be sent.
     * @param nextLink      Optional. When the validation is completed, the identity server will redirect the user to this URL.
     * @param uriInfo       Request Information.
     * @param httpHeaders   Http headers.
     * @param asyncResponse Asynchronous response.
     * @deprecated in favor of {@link SessionApi#postValidatePhone(SubmitToken, UriInfo, HttpHeaders, AsyncResponse)}.
     */
    @Deprecated
    @Operation(
        summary = "Create a session for validating a phone number.",
        description = "The identity server will send an SMS message containing a token. If that token is presented to the identity server"
            + " in the future, it indicates that that user was able to read the SMS for that phone number, and so we validate ownership"
            + " of the phone number.\nNote that homeservers offer APIs that proxy this API, adding additional behaviour on top,"
            + " for example, /register/msisdn/requestToken is designed specifically for use when registering an account and therefore will"
            + " inform the user if the phone number given is already registered on the server.",
        responses = {
            @ApiResponse(
                responseCode = "200",
                description = "Session created.",
                content = @Content(
                    schema = @Schema(
                        implementation = SessionResponse.class
                    )
                )
            ),
            @ApiResponse(
                responseCode = "400",
                description = "An error occured.",
                content = @Content(
                    schema = @Schema(
                        implementation = ErrorResponse.class
                    )
                )
            )

        }
    )
    @POST
    @Path("/validate/msisdn/requestToken")
    void createPhoneSessionDeprecated(
        @Parameter(
            name = "client_secret",
            description = "A unique string generated by the client, and used to identify the validation attempt. It must be a string"
                + " consisting of the characters [0-9a-zA-Z.=_-]. Its length must not exceed 255 characters and it must not be empty.",
            required = true
        ) @FormParam("client_secret") String clientSecret,
        @Parameter(
            description = "The two-letter uppercase ISO country code that the number in phone_number should be parsed as if it were"
                + " dialled from.",
            required = true
        ) @FormParam("country") String country,
        @Parameter(
            name = "phone_number",
            description = "The phone number to validate.",
            required = true
        ) @FormParam("phone_number") String phoneNumber,
        @Parameter(
            name = "send_attempt",
            description = "The server will only send an SMS if the send_attempt is a number greater than the most recent one which it"
                + " has seen, scoped to that country + phone_number + client_secret triple. This is to avoid repeatedly sending the"
                + " same SMS in the case of request retries between the POSTing user and the identity server. The client should increment"
                + " this value if they desire a new SMS (e.g. a reminder) to be sent.",
            required = true
        ) @FormParam("send_attempt") Long sendAttempt,
        @Parameter(
            name = "next_link",
            description = "When the validation is completed, the identity server will redirect the user to this URL."
        ) @FormParam("next_link") String nextLink,

        @Context UriInfo uriInfo,
        @Context HttpHeaders httpHeaders,
        @Suspended AsyncResponse asyncResponse
    );

    /**
     * Validate ownership of a phone number.
     * <br>
     * If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address is
     * considered to have been validated. This does not publish any information publicly, or associate the email address with any
     * Matrix user ID. Specifically, calls to /lookup will not show a binding.
     * <br>
     * The identity server is free to match the token case-insensitively, or carry out other mapping operations such as unicode
     * normalisation. Whether to do so is an implementation detail for the identity server. Clients must always pass on the token
     * without modification.
     * <br>
     * Return: {@link ValidationResponse}.
     * <p>Status code 200: The success of the validation.</p>
     *
     * @param sid           Required. The session ID, generated by the requestToken call.
     * @param clientSecret  Required. The client secret that was supplied to the requestToken call.
     * @param token         Required. The token generated by the requestToken call and sent to the user.
     * @param uriInfo       Request Information.
     * @param httpHeaders   Http headers.
     * @param asyncResponse Asynchronous response.
     * @deprecated in favor of {@link SessionApi#postValidateEmail(SubmitToken, UriInfo, HttpHeaders, AsyncResponse)}.
     */
    @Deprecated
    @Operation(
        summary = "Validate ownership of a phone number.",
        description = "If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address"
            + " is considered to have been validated. This does not publish any information publicly, or associate the email address with"
            + " any Matrix user ID. Specifically, calls to /lookup will not show a binding.\nThe identity server is free to match the token"
            + " case-insensitively, or carry out other mapping operations such as unicode normalisation. Whether to do so is"
            + " an implementation detail for the identity server. Clients must always pass on the token without modification.",
        responses = {
            @ApiResponse(
                responseCode = "200",
                description = "The success of the validation.",
                content = @Content(
                    schema = @Schema(
                        implementation = ValidationResponse.class
                    )
                )
            )
        }
    )
    @POST
    @Path("/validate/msisdn/submitToken")
    void postValidatePhoneDeprecated(
        @Parameter(
            description = "The session ID, generated by the requestToken call.",
            required = true
        ) @FormParam("sid") String sid,
        @Parameter(
            name = "client_secret",
            description = "The client secret that was supplied to the requestToken call.",
            required = true
        ) @FormParam("client_secret") String clientSecret,
        @Parameter(
            description = "The token generated by the requestToken call and sent to the user.",
            required = true
        ) @FormParam("token") String token,

        @Context UriInfo uriInfo,
        @Context HttpHeaders httpHeaders,
        @Suspended AsyncResponse asyncResponse
    );

    /**
     * Publish an association between a session and a Matrix user ID.
     * <br>
     * Future calls to /lookup for any of the session's 3pids will return this association.
     * <br>
     * Return: {@link PublishResponse}.
     * <p>Status code 200: The association was published.</p>
     * <p>Status code 400: The association was not published. If the session has not been validated, then errcode will be
     * M_SESSION_NOT_VALIDATED. If the session has timed out, then errcode will be M_SESSION_EXPIRED.</p>
     * <p>Status code 404: The Session ID or client secret were not found.</p>
     *
     * @param sid           Required. The Session ID generated by the requestToken call.
     * @param clientSecret  Required. The client secret passed to the requestToken call.
     * @param mxid          Required. The Matrix user ID to associate with the 3pids.
     * @param uriInfo       Request Information.
     * @param httpHeaders   Http headers.
     * @param asyncResponse Asynchronous response.
     * @deprecated in favor of {@link ValidationApi#bind(PublishRequest, UriInfo, HttpHeaders, AsyncResponse)}.
     */
    @Deprecated
    @Operation(
        summary = "Publish an association between a session and a Matrix user ID.",
        description = "Future calls to /lookup for any of the session's 3pids will return this association.",
        responses = {
            @ApiResponse(
                responseCode = "200",
                description = "The association was published.",
                content = @Content(
                    schema = @Schema(
                        implementation = PublishResponse.class
                    )
                )
            ),
            @ApiResponse(
                responseCode = "400",
                description = "The association was not published. If the session has not been validated, then errcode will be"
                    + " M_SESSION_NOT_VALIDATED. If the session has timed out, then errcode will be M_SESSION_EXPIRED.",
                content = @Content(
                    schema = @Schema(
                        implementation = ErrorResponse.class
                    )
                )
            ),
            @ApiResponse(
                responseCode = "404",
                description = "he Session ID or client secret were not found.",
                content = @Content(
                    schema = @Schema(
                        implementation = ErrorResponse.class
                    )
                )
            )
        }
    )
    @POST
    @Path("/bind")
    void publishDeprecated(
        @Parameter(
            description = "The Session ID generated by the requestToken call.",
            required = true
        ) @FormParam("sid") String sid,
        @Parameter(
            name = "client_secret",
            description = "The client secret passed to the requestToken call.",
            required = true
        ) @FormParam("client_secret") String clientSecret,
        @Parameter(
            description = "The Matrix user ID to associate with the 3pids.",
            required = true
        ) @FormParam("mxid") String mxid,

        @Context UriInfo uriInfo,
        @Context HttpHeaders httpHeaders,
        @Suspended AsyncResponse asyncResponse
    );
}
