/*
 * Copyright sablintolya@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.ma1uta.matrix.identity.api;

import io.github.ma1uta.matrix.EmptyResponse;
import io.github.ma1uta.matrix.identity.model.associations.ValidationResponse;
import io.github.ma1uta.matrix.identity.model.session.EmailRequestToken;
import io.github.ma1uta.matrix.identity.model.session.PhoneRequestToken;
import io.github.ma1uta.matrix.identity.model.session.SubmitToken;
import io.github.ma1uta.matrix.thirdpid.SessionResponse;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.container.AsyncResponse;
import javax.ws.rs.container.Suspended;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;

/**
 * The flow for creating an association is session-based.
 */
@Api(
    value = "Session"
)
@Path("/_matrix/identity/api/v1")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public interface SessionApi {

    /**
     * Create a session for validating an email address.
     * <br>
     * The identity server will send an email containing a token. If that token is presented to the identity server in the future,
     * it indicates that that user was able to read the email for that email address, and so we validate ownership of the email address.
     * <br>
     * Note that homeservers offer APIs that proxy this API, adding additional behaviour on top, for example,
     * /register/email/requestToken is designed specifically for use when registering an account and therefore will inform the user
     * if the email address given is already registered on the server.
     * <br>
     * Return: {@link SessionResponse}.
     * <p> Status code 200: Session created.</p>
     * <p>Status code 400: An error ocurred. Some possible errors are:</p>
     * <ul>
     * <li>M_INVALID_EMAIL: The email address provided was invalid.</li>
     * <li>M_EMAIL_SEND_ERROR: The validation email could not be sent.</li>
     * </ul>
     *
     * @param request        JSON body request.
     * @param servletRequest Servlet request.
     * @param asyncResponse  Asynchronous response.
     */
    @ApiOperation(
        value = "Create a session for validating an email address.",
        notes = "The identity server will send an email containing a token. If that token is presented to the identity server in"
            + " the future, it indicates that that user was able to read the email for that email address, and so we validate ownership"
            + " of the email address.\nNote that homeservers offer APIs that proxy this API, adding additional behaviour on top,"
            + " for example,/register/email/requestToken is designed specifically for use when registering an account and therefore will"
            + " inform the user if the email address given is already registered on the server.",
        response = SessionResponse.class
    )
    @ApiResponses( {
        @ApiResponse(code = 200, message = "Session created."),
        @ApiResponse(code = 400, message = "An error ocurred.")
    })
    @POST
    @Path("/validate/email/requestToken")
    void createEmailSession(
        @ApiParam(
            value = "JSON body request."
        ) EmailRequestToken request,

        @Context HttpServletRequest servletRequest,
        @Suspended AsyncResponse asyncResponse
    );

    /**
     * Validate ownership of an email address.
     * <br>
     * If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address is
     * considered to have been validated. This does not publish any information publicly, or associate the email address with any
     * Matrix user ID. Specifically, calls to /lookup will not show a binding.
     * <br>
     * The identity server is free to match the token case-insensitively, or carry out other mapping operations such as unicode
     * normalisation. Whether to do so is an implementation detail for the identity server. Clients must always pass on the token
     * without modification.
     * <br>
     * Return: {@link ValidationResponse}.
     * <p>Status code 200: The success of the validation.</p>
     *
     * @param request        JSON body request.
     * @param servletRequest Servlet request.
     * @param asyncResponse  Asynchronous response.
     */
    @ApiOperation(
        value = "Validate ownership of an email address.",
        notes = "If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address is"
            + " considered to have been validated. This does not publish any information publicly, or associate the email address with any"
            + " Matrix user ID. Specifically, calls to /lookup will not show a binding.\nThe identity server is free to match the token"
            + " case-insensitively, or carry out other mapping operations such as unicode normalisation. Whether to do so is"
            + " an implementation detail for the identity server. Clients must always pass on the token without modification.",
        response = ValidationResponse.class
    )
    @ApiResponses( {
        @ApiResponse(code = 200, message = "The success of the validation.")
    })
    @POST
    @Path("/validate/email/submitToken")
    void postValidateEmail(
        @ApiParam(
            value = "JSON body request.",
            required = true
        ) SubmitToken request,

        @Context HttpServletRequest servletRequest,
        @Suspended AsyncResponse asyncResponse
    );

    /**
     * Validate ownership of an email address.
     * <br>
     * If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address is
     * considered to have been validated. This does not publish any information publicly, or associate the email address with
     * any Matrix user ID. Specifically, calls to /lookup will not show a binding.
     * <br>
     * Note that, in contrast with the POST version, this endpoint will be used by end-users, and so the response should be human-readable.
     * <br>
     * Return: {@link EmptyResponse}.
     * <p>Status code 200: Email address is validated.</p>
     * <p>Status code 3xx: Email address is validated, and the next_link parameter was provided to the requestToken call.
     * The user must be redirected to the URL provided by the next_link parameter.</p>
     * <p>Status code 4xx: Validation failed.</p>
     *
     * @param sid            Required. The session ID, generated by the requestToken call.
     * @param clientSecret   Required. The client secret that was supplied to the requestToken call.
     * @param token          Required. The token generated by the requestToken call and emailed to the user.
     * @param servletRequest Servlet request.
     * @param asyncResponse  Asynchronous response.
     */
    @ApiOperation(
        value = "Validate ownership of an email address.",
        notes = "If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address is"
            + " considered to have been validated. This does not publish any information publicly, or associate the email address with any"
            + " Matrix user ID. Specifically, calls to /lookup will not show a binding.\nThe identity server is free to match the token"
            + " case-insensitively, or carry out other mapping operations such as unicode normalisation. Whether to do so is"
            + " an implementation detail for the identity server. Clients must always pass on the token without modification.",
        response = EmptyResponse.class
    )
    @ApiResponses( {
        @ApiResponse(code = 200, message = "Email address is validated."),
        @ApiResponse(code = 302, message = "Email address is validated, and the next_link parameter was provided to the requestToken call."
            + " The user must be redirected to the URL provided by the next_link parameter."),
        @ApiResponse(code = 400, message = "Validation failed.")
    })
    @GET
    @Path("/validate/email/submitToken")
    void getValidateEmail(
        @ApiParam(
            value = "The session ID, generated by the requestToken call.",
            required = true
        ) @QueryParam("sid") String sid,
        @ApiParam(
            value = "The client secret that was supplied to the requestToken call.",
            required = true
        ) @QueryParam("client_secret") String clientSecret,
        @ApiParam(
            value = "The token generated by the requestToken call and emailed to the user.",
            required = true
        ) @QueryParam("token") String token,

        @Context HttpServletRequest servletRequest,
        @Suspended AsyncResponse asyncResponse
    );

    /**
     * Create a session for validating a phone number.
     * <br>
     * The identity server will send an SMS message containing a token. If that token is presented to the identity server in the future,
     * it indicates that that user was able to read the SMS for that phone number, and so we validate ownership of the phone number.
     * <br>
     * Note that homeservers offer APIs that proxy this API, adding additional behaviour on top, for example, /register/msisdn/requestToken
     * is designed specifically for use when registering an account and therefore will inform the user if the phone number given is already
     * registered on the server.
     * <br>
     * Return: {@link SessionResponse}.
     * <p>Status code 200: Session created.</p>
     * <p>Status code 400: An error ocurred. Some possible errors are:</p>
     * <ul>
     * <li>M_INVALID_ADDRESS: The phone number provided was invalid.</li>
     * <li>M_SEND_ERROR: The validation SMS could not be sent.</li>
     * <li>M_DESTINATION_REJECTED: The identity server cannot deliver an SMS to the provided country or region.</li>
     * </ul>
     *
     * @param request        JSON body request.
     * @param servletRequest Servlet request.
     * @param asyncResponse  Asynchronous response.
     */
    @ApiOperation(
        value = "Create a session for validating a phone number.",
        notes = "The identity server will send an SMS message containing a token. If that token is presented to the identity server"
            + " in the future, it indicates that that user was able to read the SMS for that phone number, and so we validate ownership"
            + " of the phone number.\nNote that homeservers offer APIs that proxy this API, adding additional behaviour on top,"
            + " for example, /register/msisdn/requestToken is designed specifically for use when registering an account and therefore will"
            + " inform the user if the phone number given is already registered on the server.",
        response = SessionResponse.class
    )
    @ApiResponses( {
        @ApiResponse(code = 200, message = "Session created."),
        @ApiResponse(code = 400, message = "An error occured.")
    })
    @POST
    @Path("/validate/msisdn/requestToken")
    void createPhoneSession(
        @ApiParam(
            value = "JSON body request",
            required = true
        ) PhoneRequestToken request,

        @Context HttpServletRequest servletRequest,
        @Suspended AsyncResponse asyncResponse
    );

    /**
     * Validate ownership of a phone number.
     * <br>
     * If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address is
     * considered to have been validated. This does not publish any information publicly, or associate the email address with any
     * Matrix user ID. Specifically, calls to /lookup will not show a binding.
     * <br>
     * The identity server is free to match the token case-insensitively, or carry out other mapping operations such as unicode
     * normalisation. Whether to do so is an implementation detail for the identity server. Clients must always pass on the token
     * without modification.
     * <br>
     * Return: {@link ValidationResponse}.
     * <p>Status code 200: The success of the validation.</p>
     *
     * @param request        JSON body request.
     * @param servletRequest Servlet request.
     * @param asyncResponse  Asynchronous response.
     */
    @ApiOperation(
        value = "Validate ownership of a phone number.",
        notes = "If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address is"
            + " considered to have been validated. This does not publish any information publicly, or associate the email address with any"
            + " Matrix user ID. Specifically, calls to /lookup will not show a binding.\nThe identity server is free to match the token"
            + " case-insensitively, or carry out other mapping operations such as unicode normalisation. Whether to do so is"
            + " an implementation detail for the identity server. Clients must always pass on the token without modification.",
        response = ValidationResponse.class
    )
    @ApiResponses( {
        @ApiResponse(code = 200, message = "The success of the validation.")
    })
    @POST
    @Path("/validate/msisdn/submitToken")
    void postValidatePhone(
        @ApiParam(
            value = "JSON body request.",
            required = true
        ) SubmitToken request,

        @Context HttpServletRequest servletRequest,
        @Suspended AsyncResponse asyncResponse
    );

    /**
     * Validate ownership of a phone number.
     * <br>
     * If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address is
     * considered to have been validated. This does not publish any information publicly, or associate the email address with
     * any Matrix user ID. Specifically, calls to /lookup will not show a binding.
     * <br>
     * Note that, in contrast with the POST version, this endpoint will be used by end-users, and so the response should be human-readable.
     * <br>
     * Return: {@link EmptyResponse}.
     * <p>Status code 200: Phone number is validated.</p>
     * <p>Status code 3xx: Phone number is validated, and the next_link parameter was provided to the requestToken call.
     * The user must be redirected to the URL provided by the next_link parameter.</p>
     * <p>Status code 4xx: Validation failed.</p>
     *
     * @param sid            Required. The session ID, generated by the requestToken call.
     * @param clientSecret   Required. The client secret that was supplied to the requestToken call.
     * @param token          Required. The token generated by the requestToken call and sent to the user.
     * @param servletRequest Servlet request.
     * @param asyncResponse  Asynchronous response.
     */
    @ApiOperation(
        value = "Validate ownership of an email address.",
        notes = "If the three parameters are consistent with a set generated by a requestToken call, ownership of the email address is"
            + " considered to have been validated. This does not publish any information publicly, or associate the email address with any"
            + " Matrix user ID. Specifically, calls to /lookup will not show a binding.\nThe identity server is free to match the token"
            + " case-insensitively, or carry out other mapping operations such as unicode normalisation. Whether to do so is"
            + " an implementation detail for the identity server. Clients must always pass on the token without modification.\n"
            + " Note: for backwards compatibility with previous drafts of this specification, the parameters may also be specified"
            + "as application/x-form-www-urlencoded data. However, this usage is deprecated.",
        response = EmptyResponse.class
    )
    @ApiResponses( {
        @ApiResponse(code = 200, message = "Phone number is validated."),
        @ApiResponse(code = 302, message = "Email address is validated, and the next_link parameter was provided to the requestToken call."
            + " The user must be redirected to the URL provided by the next_link parameter."),
        @ApiResponse(code = 400, message = "Validation failed.")
    })
    @GET
    @Path("/validate/msisdn/submitToken")
    void getValidatePhone(
        @ApiParam(
            value = "The session ID, generated by the requestToken call.",
            required = true
        ) @QueryParam("sid") String sid,
        @ApiParam(
            value = "The client secret that was supplied to the requestToken call.",
            required = true
        ) @QueryParam("client_secret") String clientSecret,
        @ApiParam(
            value = "The token generated by the requestToken call and sent to the user.",
            required = true
        ) @QueryParam("token") String token,

        @Context HttpServletRequest servletRequest,
        @Suspended AsyncResponse asyncResponse
    );
}
