/*
 * Copyright sablintolya@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.ma1uta.matrix.client.api;

import io.github.ma1uta.matrix.EmptyResponse;
import io.github.ma1uta.matrix.client.model.auth.LoginRequest;
import io.github.ma1uta.matrix.client.model.auth.LoginResponse;

import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

/**
 * A client can obtain access tokens using the /login API.
 * <p/>
 * Note that this endpoint does not currently use the user-interactive authentication API.
 * <p/>
 * <a href="https://matrix.org/docs/spec/client_server/r0.3.0.html#login">Specification.</a>
 *
 * @author ma1uta
 */
@Path("/_matrix/client/r0")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public interface AuthApi {

    /**
     * Authenticates the user, and issues an access token they can use to authorize themself in subsequent requests.
     * <p/>
     * If the client does not supply a device_id, the server must auto-generate one.
     * <p/>
     * The returned access token must be associated with the device_id supplied by the client or generated by the server.
     * The server may invalidate any access token previously associated with that device.
     *
     * @param loginRequest {@link LoginRequest}
     * @return <p>Status code 200: The user has been authenticated.</p>
     * <p>Status code 400: Part of the request was invalid. For example, the login type may not be recognised.</p>
     * <p>Status code 401: The login attempt failed. For example, the password may have been incorrect.</p>
     * <p>Status code 429: This request was rate-limited.</p>
     *
     * <a href="https://matrix.org/docs/spec/client_server/r0.3.0.html#relationship-between-access-tokens-and-devices>
     * See Relationship between access tokens and devices.</a>
     */
    @POST
    @Path("/login")
    LoginResponse login(LoginRequest loginRequest);

    /**
     * Invalidates an existing access token, so that it can no longer be used for authorization.
     * <p/>
     * <b>Requires auth</b>: Yes.
     * <p/>
     * The access token used in the request was successfully invalidated.
     *
     * @return Status code 200: The access token used in the request was succesfully invalidated.
     */
    @POST
    @Path("/logout")
    EmptyResponse logout();
}
