/*
 * Copyright sablintolya@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.ma1uta.matrix.identity.model.session;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * JSON body request of the validation an email association.
 */
public class EmailSubmitToken {

    /**
     * Required. The session ID, generated by the requestToken call.
     */
    private String sid;

    /**
     * Required. The client secret that was supplied to the requestToken call.
     */
    @JsonProperty("client_secret")
    private String clientSecret;

    /**
     * Required. The token generated by the requestToken call and emailed to the user.
     */
    private String token;

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }
}
