/*
 * Copyright sablintolya@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.ma1uta.matrix.identity.model.validation;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * JSON body request of the bind api.
 */
@Schema(
    description = "JSON body request of the bind api."
)
public class PublishRequest {

    /**
     * Required. The Session ID generated by the requestToken call.
     */
    @Schema(
        description = "The Session ID generated by the requestToken call.",
        required = true
    )
    private String sid;

    /**
     * Required. The client secret passed to the requestToken call.
     */
    @Schema(
        name = "client_secret",
        description = "The client secret passed to the requestToken call.",
        required = true
    )
    @JsonProperty("client_secret")
    private String clientSecret;

    /**
     * Required. The Matrix user ID to associate with the 3pids.
     */
    @Schema(
        description = "The Matrix user ID to associate with the 3pids.",
        required = true
    )
    private String mxid;

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    public String getMxid() {
        return mxid;
    }

    public void setMxid(String mxid) {
        this.mxid = mxid;
    }
}
