/*
 * Copyright sablintolya@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.ma1uta.matrix.identity.model.validation;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.json.bind.annotation.JsonbProperty;

/**
 * Unbind request.
 */
@Schema(
    description = "Unbind request."
)
public class UnbindRequest {

    /**
     * The Session ID generated by the requestToken call.
     */
    @Schema(
        description = "The Session ID generated by the requestToken call."
    )
    private String sid;

    /**
     * The client secret passed to the requestToken call.
     */
    @Schema(
        name = "client_secret",
        description = "The client secret passed to the requestToken call."
    )
    @JsonbProperty("client_secret")
    private String clientSecret;

    /**
     * Required. The Matrix user ID to remove from the 3pids.
     */
    @Schema(
        description = "The Matrix user ID to remove from the 3pids.",
        required = true
    )
    private String mxid;

    /**
     * Required. The 3PID to remove.
     * Must match the 3PID used to generate the session if using sid and client_secret to authenticate this request.
     */
    @Schema(
        description = "The 3PID to remove. Must match the 3PID used to generate the session if using sid and client_secret"
            + " to authenticate this request.",
        required = true
    )
    private ThreePid threepid;

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    @JsonProperty("client_secret")
    public String getClientSecret() {
        return clientSecret;
    }

    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    public String getMxid() {
        return mxid;
    }

    public void setMxid(String mxid) {
        this.mxid = mxid;
    }

    public ThreePid getThreepid() {
        return threepid;
    }

    public void setThreepid(ThreePid threepid) {
        this.threepid = threepid;
    }
}
