package io.github.ma1uta.matrix.server.model.bind;

import lombok.Getter;
import lombok.Setter;

import java.util.Map;

/**
 * Signed part of the invitation request.
 */
@Getter
@Setter
public class Signed {

    /**
     * Owner of the 3pid.
     */
    private String mxid;

    /**
     * Token which generated by server.
     */
    private String token;

    /**
     * Signatures by long-term identity server key.
     */
    private Map<String, Map<String, String>> signatures;
}
