/*
 * Copyright sablintolya@gmail.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.ma1uta.matrix;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Map;

/**
 * Signed part of the invitation request.
 */
@ApiModel(description = "Signed part of the invitation request.")
public class Signed {

    /**
     * Owner of the 3pid.
     */
    @ApiModelProperty("Owner of the 3pid.")
    private String mxid;

    /**
     * Token which generated by server.
     */
    @ApiModelProperty("Token which generated by server.")
    private String token;

    /**
     * Signatures by long-term identity server key.
     */
    @ApiModelProperty("Signatures by long-term identity server key.")
    private Map<String, Map<String, String>> signatures;

    public String getMxid() {
        return mxid;
    }

    public void setMxid(String mxid) {
        this.mxid = mxid;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Map<String, Map<String, String>> getSignatures() {
        return signatures;
    }

    public void setSignatures(Map<String, Map<String, String>> signatures) {
        this.signatures = signatures;
    }
}
